name: jackknife-validation
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - arviz
  - pymc>=4.2
  - mkl
  - mkl-service
  - graphviz
  - pydot
  - numpy >= 1.24
  - scipy
  - scikit-learn >= 1.2
  - statsmodels
  - pandas >= 1.5
  - numpy
  - bottleneck
  - jupyterlab >= 3.6
  - ipykernel >= 6.21
  - nodejs
  - widgetsnbextension
  - ipywidgets
  - matplotlib
  - seaborn
  - bokeh
  - pytables
  - pip
  # - pip:
  #   - --trusted-host onzo-pypi.s3-website-eu-west-1.amazonaws.com
  #   - --extra-index-url http://onzo-pypi.s3-website-eu-west-1.amazonaws.com
  #   - analytics-duc
